# Generated by Django 3.0.4 on 2020-03-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('handle', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
