# Generated by Django 2.2.9 on 2020-02-22 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='user_name',
            new_name='handle',
        ),
    ]
