# Generated by Django 2.2.9 on 2020-02-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200222_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
