# Generated by Django 3.0.4 on 2020-03-14 00:58

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choicename', models.CharField(max_length=50, verbose_name='曜日の希望')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genrename', models.CharField(max_length=50, verbose_name='ジャンル')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instname', models.CharField(max_length=50, verbose_name='パート')),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefname', models.CharField(max_length=50, verbose_name='都道府県')),
            ],
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('sound', models.FileField(null=True, upload_to=app.models.get_media_sound_path, verbose_name='音源')),
                ('text', models.TextField(verbose_name='本文')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('favorite', models.TextField(null=True, verbose_name='好きなアーティスト')),
                ('active_area', models.ManyToManyField(to='app.Prefecture', verbose_name='活動エリア')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('days_of_theweek', models.ManyToManyField(max_length=50, null=True, related_name='days_oftheweek', to='app.DaysOfTheWeek', verbose_name='活動の曜日')),
                ('genre', models.ManyToManyField(null=True, to='app.Genre', verbose_name='ジャンル')),
                ('mypart', models.ManyToManyField(null=True, related_name='mypart', to='app.Instrument', verbose_name='投稿者のパート')),
                ('recruite_part', models.ManyToManyField(null=True, related_name='recruite_part', to='app.Instrument', verbose_name='募集パート')),
            ],
        ),
    ]
