# Generated by Django 2.2.9 on 2020-01-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcontent',
            old_name='actv_area',
            new_name='active_area',
        ),
    ]
