# Generated by Django 2.2.9 on 2020-01-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200130_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
