# Generated by Django 2.2.9 on 2020-01-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200130_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='genre',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='active_area',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='mypart',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='yourparts',
            field=models.BooleanField(default=True),
        ),
    ]
