# Generated by Django 2.2.9 on 2020-01-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200131_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcontent',
            old_name='yourparts',
            new_name='yourpart',
        ),
    ]
