# Generated by Django 2.2.9 on 2020-02-04 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200204_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcontent',
            name='active_area',
        ),
        migrations.RemoveField(
            model_name='postcontent',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='postcontent',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='postcontent',
            name='mypart',
        ),
        migrations.RemoveField(
            model_name='postcontent',
            name='sound',
        ),
        migrations.RemoveField(
            model_name='postcontent',
            name='yourpart',
        ),
    ]
