# Generated by Django 2.2.9 on 2020-02-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200204_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='favorite',
            field=models.TextField(null=True),
        ),
    ]
