# Generated by Django 2.2.9 on 2020-02-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_postcontent_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='sound',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
