# Generated by Django 2.2.9 on 2020-02-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200204_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='active_area',
            field=models.BooleanField(choices=[('北海道', '北海道'), ('青森県', '青森県'), ('岩手県', '岩手県'), ('宮城県', '宮城県'), ('秋田県', '秋田県'), ('山形県', '山形県'), ('福島県', '福島県'), ('東京都', '東京都'), ('神奈川県', '神奈川県'), ('埼玉県', '埼玉県'), ('千葉県', '千葉県'), ('茨城県', '茨城県'), ('栃木県', '栃木県'), ('群馬県', '群馬県'), ('山梨県', '山梨県'), ('新潟県', '新潟県'), ('長野県', '長野県'), ('富山県', '富山県'), ('石川県', '石川県'), ('福井県', '福井県'), ('愛知県', '愛知県'), ('岐阜県', '岐阜県'), ('静岡県', '静岡県'), ('三重県', '三重県'), ('大阪府', '大阪府'), ('兵庫県', '兵庫県'), ('京都府', '京都府'), ('滋賀県', '滋賀県'), ('奈良県', '奈良県'), ('和歌山県', '和歌山県'), ('鳥取県', '鳥取県'), ('島根県', '島根県'), ('岡山県', '岡山県'), ('広島県', '広島県'), ('山口県', '山口県'), ('徳島県', '徳島県'), ('香川県', '香川県'), ('愛媛県', '愛媛県'), ('高知県', '高知県'), ('福岡県', '福岡県'), ('佐賀県', '佐賀県'), ('長崎県', '長崎県'), ('熊本県', '熊本県'), ('大分県', '大分県'), ('宮崎県', '宮崎県'), ('鹿児島県', '鹿児島県'), ('沖縄県', '沖縄県')], default=True, null=True, verbose_name='活動エリア（都道府県）'),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='favorite',
            field=models.TextField(null=True, verbose_name='好きなアーティスト'),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='sound',
            field=models.FileField(null=True, upload_to='uploads', verbose_name='デモ音源'),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='text',
            field=models.TextField(verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='title',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
    ]
