# Generated by Django 2.2.9 on 2020-02-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200205_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genrename', models.CharField(max_length=50, verbose_name='ジャンル')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instname', models.CharField(max_length=50, verbose_name='パート')),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefname', models.CharField(max_length=50, verbose_name='都道府県')),
            ],
        ),
        migrations.RemoveField(
            model_name='postcontent',
            name='active_area',
        ),
        migrations.AddField(
            model_name='postcontent',
            name='genre',
            field=models.ManyToManyField(null=True, to='app.Genre', verbose_name='ジャンル'),
        ),
        migrations.AddField(
            model_name='postcontent',
            name='mypart',
            field=models.ManyToManyField(null=True, related_name='mypart', to='app.Instrument', verbose_name='投稿者のパート'),
        ),
        migrations.AddField(
            model_name='postcontent',
            name='recruite_part',
            field=models.ManyToManyField(null=True, related_name='recruite_part', to='app.Instrument', verbose_name='募集パート'),
        ),
        migrations.AddField(
            model_name='postcontent',
            name='active_area',
            field=models.ManyToManyField(null=True, to='app.Prefecture', verbose_name='活動エリア（都道府県）'),
        ),
    ]
