# Generated by Django 2.2.9 on 2020-02-06 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200206_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postcontent',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
