# Generated by Django 2.2.9 on 2020-02-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200206_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
