# Generated by Django 2.2.9 on 2020-02-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200207_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcontent',
            name='sound',
        ),
        migrations.AddField(
            model_name='postcontent',
            name='sound',
            field=models.FileField(null=True, upload_to='get_media_sound_path', verbose_name='音源'),
        ),
        migrations.DeleteModel(
            name='SoundFile',
        ),
    ]
