# Generated by Django 2.2.9 on 2020-02-08 13:02

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200207_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='sound',
            field=models.FileField(null=True, upload_to=app.models.get_media_sound_path, verbose_name='音源'),
        ),
    ]
