# Generated by Django 2.2.9 on 2020-02-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200208_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='day_of_theweek',
            field=models.BooleanField(choices=[('土日', '土日'), ('平日', '平日'), ('指定なし', '指定なし')], null=True),
        ),
    ]
