# Generated by Django 2.2.9 on 2020-02-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200210_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='days_of_theweek',
            field=models.BooleanField(choices=[('土日', '土日'), ('平日', '平日'), ('指定なし', '指定なし')], null=True, verbose_name='活動の曜日'),
        ),
    ]
