# Generated by Django 2.2.9 on 2020-02-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200210_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='days_of_theweek',
            field=models.CharField(choices=[('土日', '土日'), ('平日', '平日'), ('指定なし', '指定なし')], max_length=50, null=True, verbose_name='活動の曜日'),
        ),
    ]
