# Generated by Django 2.2.9 on 2020-02-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200210_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choicename', models.CharField(max_length=50, verbose_name='曜日の希望')),
            ],
        ),
        migrations.RemoveField(
            model_name='postcontent',
            name='days_of_theweek',
        ),
        migrations.AddField(
            model_name='postcontent',
            name='days_of_theweek',
            field=models.ManyToManyField(max_length=50, null=True, related_name='days_oftheweek', to='app.DaysOfTheWeek', verbose_name='活動の曜日'),
        ),
    ]
