# Generated by Django 2.2.9 on 2020-03-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200227_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='active_area',
            field=models.ManyToManyField(to='app.Prefecture', verbose_name='活動エリア'),
        ),
    ]
